# Lecture 4: Functions, Arrays, and Files

## 0. Business Case: TechGear Monthly Sales Analysis

You are a Junior Business Analyst at TechGear.

Last class, we learned how Python stores business information using data types such as:

- Integers
- Floats
- Strings
- Booleans
- Lists
- Dictionaries

Today we will answer bigger business questions:

- How can we automate repetitive calculations?
- How can we analyze sales data efficiently?
- How can we store and retrieve data from files?

By the end of class, you will be able to build simple business analytics workflows using Python.

## 1. Warm-Up Review

Last class we created a sales record.

Can you identify the data types?

In [6]:
sale = {
    "order_id": 1001,
    "customer": "Sarah Johnson",
    "product": "Laptop",
    "units": 2,
    "price": 899.99,
    "shipped": True
}

sale

{'order_id': 1001,
 'customer': 'Sarah Johnson',
 'product': 'Laptop',
 'units': 2,
 'price': 899.99,
 'shipped': True}

### Think-Pair-Share

What data type is each value?

- order_id
- customer
- product
- units
- price
- shipped
`

## 2. Functions

Imagine your manager asks:

"What was the revenue for each product sold this month?"

Revenue is calculated using:

Revenue = Price × Quantity

We could repeatedly write:

price * quantity

However, analysts often perform the same calculation many times.

Functions allow us to automate repetitive tasks.

In [17]:
def calculate_revenue(price, quantity):
    

### Predict Before Running

What do you think this function will return?

In [48]:
def calculate_revenue(price, quantity):
    revenue = price * quantity
    return revenue

In [50]:
calculate_revenue(1200, 3)

3600

The function receives:

- price = 1200
- quantity = 3

Revenue = 1200 × 3


In [42]:
calculate_revenue(350, 10)


3500


Notice that the same function works for any product.

This is one reason functions are valuable for analysts.

### Create a Profit Function

Many businesses track profit rather than revenue.

Profit = Revenue − Expenses

Let's automate that calculation.

In [46]:
def calculate_profit(revenue, expenses):
    return revenue - expenses

In [52]:
calculate_profit(5000, 3200)

1800

In [2]:
def calculate_profit(revenue, expenses):
    profit = revenue - expenses
    print("The profit is $" + str(profit) + ".")

In [4]:
calculate_profit(30000, 540293)


The profit is $-510293.


### Your Turn

Use the function to calculate the profit for:

Revenue = 8,000

Expenses = 5,600

## 3. Monthly Sales

Suppose TechGear recorded the following monthly sales:

January = 120

February = 150

March = 135

April = 170

We could store each value separately, but this becomes inefficient as datasets grow.

In [56]:
january = 120
february = 150
march = 135
april = 170

Instead, Python allows us to store related values together.

This is much closer to how business datasets are organized.

In [59]:
sales_list = [120, 150, 135, 170]

sales_list

[120, 150, 135, 170]

## 4. NumPy Arrays

NumPy is a powerful Python library used in:

- Data Analytics
- Machine Learning
- Artificial Intelligence
- Scientific Computing

Arrays allow us to perform calculations on many values simultaneously.

In [62]:
import numpy as np

In [64]:
monthly_sales = np.array([
    120,
    150,
    135,
    170
])

monthly_sales

array([120, 150, 135, 170])

### Predict Before Running

A marketing campaign increases sales by 10 units each month.

What do you think will happen?

In [67]:
monthly_sales + 10

array([130, 160, 145, 180])

NumPy applies the calculation to every value in the array.

This is called vectorized computation.

## 5. Business Performance Indicators

Managers often ask:

- Total sales?
- Average sales?
- Best month?
- Worst month?

Let's answer those questions.

In [72]:
monthly_sales.sum()

575

In [74]:
monthly_sales.mean()

143.75

In [76]:
monthly_sales.max()

170

In [78]:
monthly_sales.min()

120

### Discussion

Which KPI would be most useful for:

- A Sales Manager?
- A Marketing Manager?
- A CEO?

Why?

## 6. Why Not Just Use Lists?

A common question is:

"If lists already store data, why do we need arrays?"

In [81]:
sales_list = [120, 150, 135, 170]

sales_list * 2

[120, 150, 135, 170, 120, 150, 135, 170]

Did that do what you expected?

Let's try the same thing with a NumPy array.

In [84]:
sales_array = np.array([
    120,
    150,
    135,
    170
])

sales_array * 2

array([240, 300, 270, 340])

Arrays perform mathematical operations.

Lists focus on storing information.

This distinction will become extremely important when we start using data science libraries.

## 7. Business Files

Businesses store data in files every day.

Examples include:

- CSV files
- Excel files
- Text files

Let's create a simple sales file.

In [88]:
sales_text = """
Laptop,1200
Monitor,350
Keyboard,75
Mouse,45
"""

In [90]:
with open("sales.txt", "w") as file:
    file.write(sales_text)

print("Sales file created.")

Sales file created.


Our file now contains product sales information that can be read by Python.

### Opening a File

Before Python can read a file, it must open it.

In [94]:
file = open("sales.txt", "r")

print(file)

<_io.TextIOWrapper name='sales.txt' mode='r' encoding='cp936'>


### Reading File Contents

Let's read the entire file.

In [97]:
file = open("sales.txt", "r")

contents = file.read()

print(contents)


Laptop,1200
Monitor,350
Keyboard,75
Mouse,45



Notice that the contents are returned as a single string.

### Reading One Record at a Time

Business reports often process one transaction at a time.

In [101]:
file = open("sales.txt", "r")

for line in file:
    print(line)



Laptop,1200

Monitor,350

Keyboard,75

Mouse,45



Each line represents a business record.

### How Many Products Are Stored?

Managers often ask:

"How many records do we have?"

In [105]:
file = open("sales.txt", "r")

count = 0

for line in file:
    count += 1

print("Number of products:", count)

Number of products: 5


### Searching for Specific Information

Suppose the manager wants to find information about laptops.

In [108]:
file = open("sales.txt", "r")

for line in file:
    
    if line.startswith("Laptop"):
        print(line)

Laptop,1200



### Your Turn

Modify the code to find:

- Monitor
- Keyboard
- Mouse

## 8. Mini Analyst Project

You are preparing a report for management.

Tasks:

1. Store monthly sales in an array
2. Calculate average sales
3. Use a function to calculate revenue
4. Read product information from a file

Can you combine everything learned today?

In [112]:
import numpy as np

monthly_sales = np.array([
    120,
    150,
    135,
    170
])

def calculate_revenue(price, quantity):
    return price * quantity

average_sales = monthly_sales.mean()

revenue = calculate_revenue(1200, 3)

print("Average Sales:", average_sales)

print("Revenue:", revenue)

Average Sales: 143.75
Revenue: 3600


## 9. Exit Ticket

Before leaving class:

1. What is one benefit of using functions?

2. What is one advantage of NumPy arrays?

3. Why do businesses store information in files?

4. Which concept needs more practice?

5. How do today's topics connect to business analytics?